# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Preferred Shift',
            },
        ),
        migrations.RenameModel(
            old_name='Shift',
            new_name='AssignedShift',
        ),
        migrations.AlterModelOptions(
            name='assignedshift',
            options={'verbose_name': 'Shift'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
        migrations.AddField(
            model_name='preferredshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Employee'),
        ),
    ]
