# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20160227_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferredshift',
            options={'verbose_name': 'Preferred Time'},
        ),
        migrations.AddField(
            model_name='assignedshift',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferredshift',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignedshift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='assignedshift',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='preferredshift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='preferredshift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
